// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApiProject.Database.Context;

#nullable disable

namespace MyApiProject.Database.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApiProject.DomainLayer.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 58,
                            Name = "Sivas",
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Antalya",
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bolu",
                            Status = 0
                        },
                        new
                        {
                            Id = 34,
                            Name = "İstanbul",
                            Status = 0
                        });
                });

            modelBuilder.Entity("MyApiProject.DomainLayer.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("District");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 58,
                            Name = "Kangal",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CityId = 58,
                            Name = "Yıldızeli",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CityId = 58,
                            Name = "Suşehri",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CityId = 7,
                            Name = "Muratpaşa",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            CityId = 7,
                            Name = "Alanya",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            CityId = 14,
                            Name = "Gerede",
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            CityId = 7,
                            Name = "Kemer",
                            Status = 0
                        });
                });

            modelBuilder.Entity("MyApiProject.DomainLayer.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Personnel");
                });

            modelBuilder.Entity("MyApiProject.DomainLayer.District", b =>
                {
                    b.HasOne("MyApiProject.DomainLayer.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("MyApiProject.DomainLayer.Personnel", b =>
                {
                    b.HasOne("MyApiProject.DomainLayer.District", "District")
                        .WithMany("Personnels")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("MyApiProject.DomainLayer.City", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("MyApiProject.DomainLayer.District", b =>
                {
                    b.Navigation("Personnels");
                });
#pragma warning restore 612, 618
        }
    }
}
